{"instance_id": "TSP61", "instance_filename": "TSP61_144_13_pa561.tsp.qubo.json", "solver_name": "QUBODwaveSolver", "args": ["1000", "None", "None"], "timestamps": {"start": 1702936598.056446, "end": 1702936600.188338}, "solver": {"exception": "", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench.py\", line 152, in run\n    solver = self._run(instance_id, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench_qubo.py\", line 108, in _run\n    sampler = DWaveSampler(token=self.token)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 185, in __init__\n    self.solver = self._get_solver(penalty=self._solver_penalty)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 200, in _get_solver\n    solvers = self.client.get_solvers(refresh=refresh, order_by=order_by, **filters)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\events.py\", line 105, in wrapped\n    rval = fn(*pargs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 1165, in get_solvers\n    solvers = self._fetch_solvers(**query)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\utils.py\", line 489, in wrapper\n    val = fn(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 802, in _fetch_solvers\n    data = Client._sapi_request(self.session.get, url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 1760, in _sapi_request\n    response = meth(*args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\requests\\sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\utils.py\", line 314, in request\n    return super().request(method, url, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\requests\\sessions.py\", line 747, in send\n    r.content\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\requests\\models.py\", line 899, in content\n    self._content = b\"\".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b\"\"\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nMemoryError\n", "fail_timestamp": 1702936600.188338}, "success": false, "version": "2.0.2"}