{"instance_id": "TSP34", "instance_filename": "TSP34_121_12_gr666.qubo.json", "solver_name": "QUBODwaveSolver", "args": ["1000", "None", "None"], "timestamps": {"start": 1702936168.112593, "end": 1702936174.174097}, "solver": {"exception": "Problem not accepted because user has insufficient remaining solver access time in project cWdP", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench.py\", line 152, in run\n    solver = self._run(instance_id, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench_qubo.py\", line 138, in _run\n    response=response.to_serializable(),\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dimod\\sampleset.py\", line 1779, in to_serializable\n    for name, data in self.data_vectors.items()}\n                      ^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dimod\\sampleset.py\", line 1062, in data_vectors\n    return {field: self.record[field] for field in self.record.dtype.names\n                                                   ^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dimod\\sampleset.py\", line 1121, in record\n    self.resolve()\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dimod\\sampleset.py\", line 1470, in resolve\n    samples = self._result_hook(self._future)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\composites\\embedding.py\", line 284, in async_unembed\n    sampleset = unembed_sampleset(response, embedding, source_bqm=bqm,\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\embedding\\transforms.py\", line 626, in unembed_sampleset\n    record = target_sampleset.record\n             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dimod\\sampleset.py\", line 1121, in record\n    self.resolve()\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dimod\\sampleset.py\", line 1470, in resolve\n    samples = self._result_hook(self._future)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 453, in _hook\n    raise exc\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 440, in _hook\n    return resolve(computation)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 430, in resolve\n    sampleset.resolve()\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dimod\\sampleset.py\", line 1470, in resolve\n    samples = self._result_hook(self._future)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\computation.py\", line 823, in <lambda>\n    self, lambda f: f.wait_sampleset())\n                    ^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\computation.py\", line 755, in wait_sampleset\n    result = self._load_result()\n             ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\computation.py\", line 893, in _load_result\n    raise self._exception\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 1455, in _handle_problem_status\n    raise SolverFailureError(errmsg)\ndwave.cloud.exceptions.SolverFailureError: Problem not accepted because user has insufficient remaining solver access time in project cWdP\n", "fail_timestamp": 1702936174.174097}, "success": false, "version": "2.0.2"}